openapi: 3.2.0
info:
  version: 16.10.0
  title: Amplify Platform API v1.0.0 Session API
  description: 'The Amplify Platform API provides the interface to perform the following:

    - Manage account settings and credentials

    - Manage organization settings, users, service accounts, and teams

    - Retrieve organization usage data

    - Register and manage applications

    - Retrieve application metrics and analytics

    - Retrieve user, organization, and application activity


    See the Amplify Guide for documentation and examples on how to authorize API calls to platform services.'
  contact:
    email: support@axway.com
  termsOfService: https://www.axway.com/en/axway-platform-terms-of-use
servers:
- url: https://platform.axway.com/api/v1
tags:
- name: Session
paths:
  /session/query:
    parameters: []
    post:
      summary: Axway Find Sessions
      description: 'Return sessions matching search criteria.


        ___Auth Requirement___

        - Signed-in user.


        _Allows consumer organization access_'
      externalDocs:
        description: Viewing Sessions
        url: https://docs.axway.com/bundle/platform-management/page/docs/management_guide/managing_accounts/viewing_and_editing_accounts/index.html
      tags:
      - Session
      operationId: session_query
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Response'
                - properties:
                    result:
                      title: SessionList
                      type: array
                      description: A list of Session objects.
                      items:
                        type: object
                        properties:
                          dvid:
                            type: string
                            description: Identifier for the device authorized for the session.
                          from:
                            type: string
                            description: Type of client the session was initiated by, e.g. web/cli
                          ipaddress:
                            type: object
                            description: IP Address the session was created from, anonymized to the Class C block.
                          os:
                            type: object
                            description: Name and version of the device the session is for.
                            properties:
                              name:
                                type: string
                              version:
                                type: string
                          software:
                            type: object
                            description: Name and version of the software session was created using.
                            properties:
                              name:
                                type: string
                              version:
                                type: string
                          org:
                            type: object
                            required:
                            - guid
                            - name
                            - org_id
                            unevaluatedProperties: false
                            allOf:
                            - $ref: '#/components/schemas/DefaultFields'
                            properties:
                              name:
                                type: string
                                description: Name of the organization.
                                minLength: 2
                                maxLength: 64
                                x-no-tags: true
                              org_id:
                                type: integer
                                description: Identifier for the organization
                              guid:
                                type: string
                                format: uuid
                                description: GUID identifier for the organization
                          org_id:
                            type: string
                            description: org_id of the signed-in org.
                          org_name:
                            type: string
                            description: Name of the signed-in org.
                          user:
                            type: object
                            required:
                            - email
                            - guid
                            unevaluatedProperties: false
                            properties:
                              email:
                                type: string
                                format: email
                                description: Email address of the user.
                                maxLength: 217
                              guid:
                                type: string
                                description: GUID of the user.
                          current:
                            type: boolean
                            description: Whether this is the current session making the request.
                - properties:
                    metadata:
                      $ref: '#/components/schemas/ResponseMetadata'
              examples:
                SessionQuery200Example:
                  summary: Default session_query 200 response
                  x-microcks-default: true
                  value: example_value
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                LOGIN_REQUIRED:
                  value:
                    $ref: '#/components/examples/LOGIN_REQUIRED/value'
                PARAM_INVALID:
                  value:
                    $ref: '#/components/examples/PARAM_INVALID/value'
      security:
      - SessionCookie: []
      - BearerUser: []
      parameters:
      - $ref: '#/components/parameters/fields'
        example: example_value
      - $ref: '#/components/parameters/exclude_fields'
        example: example_value
      - in: query
        name: limit
        required: false
        schema:
          type: number
          minimum: 0
          maximum: 250
          description: Number of results per page. Zero will return an empty result, but the matched count in meta will be returned.
          default: 10
        example: 1.0
      - in: query
        name: page
        required: false
        schema:
          type: number
          description: Page of results.
          default: 1
        example: 1.0
      - in: query
        name: skip
        required: false
        schema:
          type: number
          description: Number of items to skip in results, used for pagination.
          default: 0
        example: 1.0
      - in: query
        name: sort
        required: false
        schema:
          type: array
          description: Field on which to sort results, may pass multiple comma-separated. Prefix the field name with `-` for descending order.
          items:
            type: string
            enum:
            - access_token
            - created
            - dvid
            - from
            - impersonator_guid
            - ipaddress
            - is_staff
            - org_guid
            - os.name
            - os.version
            - software.name
            - software.version
            - expires
            - lastModified
            - session.email
            - session.user_guid
          default:
          - created
        example:
        - access_token
      requestBody:
        content:
          '*/*':
            schema:
              properties:
                access_token:
                  type: string
                  description: Search by session.access_token
                created:
                  type: string
                  description: Search by session.created
                from:
                  type: string
                  description: Search by session.from
                last_modified:
                  type: string
                  description: Search by lastModified
                org_guid:
                  type: string
                  description: Search by session.org_guid
                user_email:
                  type: string
                  description: Search by session.email
                user_id:
                  type: string
                  description: Search by session.user_guid
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /session:
    parameters: []
    get:
      summary: Axway Get Session
      description: 'Retrieves the active session for the user.


        ___Auth Requirement___

        - Signed-in user.


        _Allows consumer organization access_'
      tags:
      - Session
      operationId: session_find
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Response'
                - properties:
                    result:
                      type: object
                      properties:
                        sessionID:
                          type: string
                          description: The session ID.
                        user_guid:
                          type: string
                          description: GUID of the signed-in user.
                        idp:
                          type: string
                          description: GUID of the Identity Provider used to authenticate the session.
                        created:
                          type: string
                          format: date-time
                          description: Date/time the session was created.
                        org_guid:
                          $ref: '#/components/schemas/Org/properties/guid'
              examples:
                SessionFind200Example:
                  summary: Default session_find 200 response
                  x-microcks-default: true
                  value: example_value
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                LOGIN_REQUIRED:
                  value:
                    $ref: '#/components/examples/LOGIN_REQUIRED/value'
      security:
      - SessionCookie: []
      - BearerUser: []
      parameters:
      - $ref: '#/components/parameters/fields'
        example: example_value
      - $ref: '#/components/parameters/exclude_fields'
        example: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /session/{session_id}:
    parameters: []
    delete:
      summary: Axway Delete Session
      description: 'Deletes a session. This is a destructive and irreversible action.


        ___Auth Requirement___

        - Signed-in user.


        _Allows consumer organization access_'
      externalDocs:
        description: Viewing Sessions
        url: https://docs.axway.com/bundle/platform-management/page/docs/management_guide/managing_accounts/viewing_and_editing_accounts/index.html
      tags:
      - Session
      operationId: session_remove
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                LOGIN_REQUIRED:
                  value:
                    $ref: '#/components/examples/LOGIN_REQUIRED/value'
                PARAM_INVALID:
                  value:
                    $ref: '#/components/examples/PARAM_INVALID/value'
                PARAM_REQUIRED:
                  value:
                    $ref: '#/components/examples/PARAM_REQUIRED/value'
      security:
      - SessionCookie: []
      - BearerUser: []
      parameters:
      - in: path
        name: session_id
        required: true
        schema:
          type: string
          description: _id of the session.
        example: 507f1f77bcf86cd799439011
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    Response:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the request was successful.
          example: true
    Org:
      type: object
      required:
      - active
      - guid
      - name
      - org_id
      - region
      - subscriptions
      - users
      unevaluatedProperties: false
      allOf:
      - $ref: '#/components/schemas/DefaultFields'
      properties:
        _id:
          type: string
          description: The id of the organization.
          readOnly: true
          deprecated: true
          example: 507f1f77bcf86cd799439011
        account_id:
          type: integer
          description: Account ID of the organization.
          minimum: 10000
          maximum: 999999
          example: 1
        active:
          type: boolean
          description: Active state of the organization. Organizations become inactive after passing their end date.
          default: true
          example: true
        analytics:
          type: object
          description: Analytics details for the organization
          additionalProperties: false
          properties:
            token:
              type: string
              description: Token used to identify the organization.
          example:
            token: eyJhbGciOiJIUzI1NiJ9.example
        api_central:
          type: object
          description: Engage provision status
          readOnly: true
          example: {}
        branding:
          type: object
          description: Organization branding.
          additionalProperties: false
          properties:
            logo:
              type: string
              description: Logo image of the company.
          example:
            logo: example_value
        consumer_id:
          type: string
          description: Mapped ID of the consumer org from the configured Identity Provider.
          example: 507f1f77bcf86cd799439011
        created_by:
          type: object
          description: Details of the user that created the organization.
          unevaluatedProperties: false
          properties:
            client_id:
              type: string
              description: The client_id of the client that created the organization.
              readOnly: true
            email:
              type: string
              format: email
              description: Email address of the user that created the organization.
              readOnly: true
            name:
              type: string
              description: The name of the user or client that created the organization.
              readOnly: true
          example:
            client_id: 507f1f77bcf86cd799439011
            email: user@example.com
            name: Example Name
        entitlements:
          type: object
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/Entitlements'
          example: {}
        guid:
          type: string
          format: uuid
          description: GUID identifier for the organization
          example: example_value
        help_menu:
          type: object
          description: Contents of the help menu displayed in the navigation bar.
          default:
            enabled: false
          additionalProperties: false
          properties:
            enabled:
              type: boolean
              description: Whether the custom help menu is enabled.
              default: false
            defaults:
              type: boolean
              description: Whether to include the default items.
            icon:
              type: string
              description: Icon displayed in the navigation bar to show the help menu.
            items:
              type: array
              description: Custom help menu shown in the navigation bar.
              items:
                type: object
                required:
                - text
                - type
                - url
                unevaluatedProperties: false
                discriminator:
                  propertyName: type
                  mapping:
                    url: '#/components/schemas/Org/properties/help_menu/properties/items/items/oneOf/0'
                    document: '#/components/schemas/Org/properties/help_menu/properties/items/items/oneOf/1'
                oneOf:
                - type: object
                  properties:
                    type:
                      type: string
                      enum:
                      - url
                    url:
                      type: string
                      format: url
                      description: URL for the link.
                - type: object
                  properties:
                    type:
                      type: string
                      enum:
                      - document
                    url:
                      type: string
                      description: Document resource guid
                properties:
                  icon:
                    type: string
                    description: Icon displayed in the menu for the item.
                  new_tab:
                    type: boolean
                    description: Whether the link opens in a new tab.
                  provider_guid:
                    type: string
                    description: The GUID of the provider a document url is for
                  text:
                    type: string
                    description: Label for the link.
                    x-no-tags: true
                  type:
                    type: string
                    description: Type of the link.
                    enum:
                    - document
                    - url
                  url:
                    type: string
                    description: URL, relative path, or document resource guid for the link.
          example:
            enabled: true
            defaults: true
            icon: example_value
            items:
            - icon: example_value
              new_tab: true
              provider_guid: example_value
              text: example_value
              type: document
              url: https://example.com
        last_login:
          type: string
          format: date-time
          description: When the most recent session was created in the organization.
          readOnly: true
          example: '2026-04-21T00:00:00Z'
        logged_in_count:
          type: number
          description: How many session are been created in the organization.
          readOnly: true
          example: 1.0
        name:
          type: string
          description: Name of the organization.
          minLength: 2
          maxLength: 64
          x-no-tags: true
          example: Example Name
        onboarding:
          type: object
          description: Onboarding data for consumer org.
          maxProperties: 50
          writeOnly: true
          patternProperties:
            '[\w-]{21}':
              type:
              - string
              - number
              - boolean
              - array
              description: Onboarding data field value.
              items:
                type: string
                description: Onboarding data field multi-select option value.
          example: {}
        onboarding_required:
          type: array
          readOnly: true
          items:
            type: string
            pattern: '[\w-]{21}'
          example:
          - example_value
        org_id:
          type: integer
          description: Identifier for the organization
          example: 1
        origin:
          type:
          - string
          - 'null'
          description: Source from which the organization creation originated.
          enum:
          - '360'
          - sfdc
          - signup
          example: '360'
        pending:
          type: boolean
          description: Whether the organization is pending approval for a provider organization administator.
          example: true
        provider_guid:
          type: string
          format: uuid
          description: GUID identifier of the owning provider if the organization is a consumer of a marketplace.
          example: example_value
        region:
          type: string
          description: The data residency region of the organization.
          default: US
          enum:
          - US
          - EU
          - AP
          example: US
        security:
          type: object
          description: Security settings for the organization.
          additionalProperties: false
          properties:
            access_controls:
              type: object
              description: Developer visibility controls.
              additionalProperties: false
              properties:
                enviroments:
                  type: number
                  description: Developer access to environments. 0 - Developers cannot view environments, 1 - Developer may view all environemnts.
                  enum:
                  - 0
                  - 1
                service_accounts:
                  type: number
                  description: Developer access to service accounts. 0 - Developers cannot view service accounts, 1 - Developers may view service accounts in their teams, 2 - Developer may view all service accounts.
                  enum:
                  - 0
                  - 1
                  - 2
                usage:
                  type: number
                  description: Developer access to usage. 0 - Developers cannot view usage, 1 - Developer may view all usage.
                  enum:
                  - 0
                  - 1
                users:
                  type: number
                  description: Developer access to users.0 - Developers cannot view users, 1 - Developers may view administrators and users in their teams, 2 - Developer may view all users.
                  enum:
                  - 0
                  - 1
                  - 2
            allow_tooling:
              type: boolean
              description: Grant access using tooling credentials
            disable_analytics:
              type: boolean
              description: Opt out from third-party support services.
            password_policy:
              $ref: '#/components/schemas/PasswordPolicy'
            redact_personal:
              type: boolean
              description: Personal information like email addresses will be masked in UI.
              default: false
          example:
            access_controls:
              enviroments: 0
              service_accounts: 0
              usage: 0
              users: 0
            allow_tooling: true
            disable_analytics: true
            password_policy:
              length: 1
              max_length: 1
              lower: 1
              upper: 1
              special: 1
              digit: 1
              lockout: 1
              renewal: 1
              history: 1
            redact_personal: true
        subscriptions:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/Subscription'
          example:
          - end_date: '2026-04-21T00:00:00Z'
            entitlements:
            - key: example_value
              value: example_value
            governance: SaaS
            id: 507f1f77bcf86cd799439011
            opportunity_id: 1.0
            plan: example_value
            product: example_value
            product_name: Example Name
            source: API
            start_date: '2026-04-21T00:00:00Z'
        support_access_code:
          type: integer
          description: Support Access Code for the org.
          minimum: 10000
          maximum: 999999
          example: 1
        users:
          type: array
          description: List of users that are members of the organization.
          default: []
          items:
            type: object
            required:
            - guid
            - roles
            additionalProperties: false
            properties:
              guid:
                type: string
                format: uuid
                description: GUID of the user.
              idp:
                type: string
                description: GUID of the Identity Provider the user is required to authenticate with to access the organization.
              primary:
                type: boolean
                description: Whether the user is the primary contact for the organization.
              roles:
                type: array
                description: Roles within the organization.
                items:
                  type: string
                  enum:
                  - administrator
                  - developer
                  - auditor
                  - consumer
                  - usage_reporter
                  - api_central_admin
          example:
          - guid: example_value
            idp: example_value
            primary: true
            roles:
            - administrator
    Error:
      type: object
      allOf:
      - $ref: '#/components/schemas/Response'
      - type: object
        properties:
          code:
            type: number
            description: HTTP status code.
          description:
            type: string
            description: A message describing the error.
          internalCode:
            type: number
            description: Internal code.
    ResponseMetadata:
      type: object
      properties:
        count:
          type: number
          description: Number of results included in the response.
          example: 1.0
        limit:
          type: number
          description: Number of results per page.
          example: 1.0
        matched:
          type: number
          description: Total number of matched results.
          example: 1.0
        page:
          type: number
          description: Page of results.
          example: 1.0
        pages:
          type: number
          description: Total number of pages of results.
          example: 1.0
        skip:
          type: number
          description: Number of results skipped in pagination.
          example: 1.0
    DefaultFields:
      type: object
      unevaluatedProperties: false
      properties:
        created:
          type: string
          format: date-time
          description: Date created.
          readOnly: true
          example: '2026-04-21T00:00:00Z'
        created_by:
          type: object
          description: Creator user or client.
          readOnly: true
          properties:
            guid:
              type: string
              description: '`guid` of the creator.'
            type:
              type: string
              description: Type of the creator.
              enum:
              - user
              - client
          example:
            guid: example_value
            type: user
        updated:
          type: string
          format: date-time
          description: Date last updated.
          readOnly: true
          example: '2026-04-21T00:00:00Z'
  parameters:
    fields:
      name: fields
      in: query
      description: A list of fields to include in the response.
      schema:
        type: array
        items:
          type: string
    exclude_fields:
      name: exclude_fields
      in: query
      description: A list of fields to exclude from the response.
      schema:
        type: array
        items:
          type: string
  examples:
    PARAM_REQUIRED:
      value:
        success: false
        description: '"%s" is a required parameter.'
        code: 400
        internalCode: 77
    PARAM_INVALID:
      value:
        success: false
        description: '"%s" contained an invalid value.'
        code: 400
        internalCode: 74
    LOGIN_REQUIRED:
      value:
        success: false
        description: Sign-in Required
        code: 401
  securitySchemes:
    AuthToken:
      description: Auth token for internal services
      type: apiKey
      in: header
      name: x-auth-token
    BearerClient:
      description: Service account access token
      type: http
      scheme: bearer
      bearerFormat: jwt
    BearerService:
      description: Service account access token for an internal client
      type: http
      scheme: bearer
      bearerFormat: jwt
    BearerUser:
      description: AxwayID user session access token
      type: http
      scheme: bearer
      bearerFormat: jwt
    MFA:
      description: Multi-factor authentication code
      type: apiKey
      in: header
      name: x-auth-code
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.axway.com/auth/realms/Broker/protocol/openid-connect/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://login.axway.com/auth/realms/Broker/openid-connect/auth
          tokenUrl: https://login.axway.com/auth/realms/Broker/openid-connect/token
          scopes: {}
        implicit:
          authorizationUrl: https://login.axway.com/auth/realms/Broker/openid-connect/auth
          scopes: {}
    Password:
      description: User password
      type: apiKey
      in: header
      name: x-auth-password
    SessionCookie:
      description: Platform session cookie
      type: apiKey
      in: cookie
      name: connect.sid
